service: birthday-service

plugins:
  - serverless-esbuild
  - serverless-offline

provider:
  name: aws
  runtime: nodejs20.x
  stage: ${opt:stage, 'dev'}
  region: ap-southeast-1
  
  environment:
    DB_HOST: ${self:custom.rds.host}
    DB_PORT: ${self:custom.rds.port}
    DB_NAME: ${self:custom.rds.database}
    DB_USER: ${self:custom.rds.username}
    # Use AWS Parameter Store for password in non-local environments
    DB_PASSWORD: ${self:custom.rds.password}
    WEBHOOK_ENDPOINT: ${env:WEBHOOK_ENDPOINT, 'https://eog8uvm3yyo7caf.m.pipedream.net'}
    IS_OFFLINE: ${env:IS_OFFLINE, 'false'}

  iam:
    role:
      statements:
        - Effect: Allow
          Action:
            - ssm:GetParameter
            - ssm:GetParameters
          Resource: 
            - !Sub arn:aws:ssm:${AWS::Region}:${AWS::AccountId}:parameter/birthday-service/${self:provider.stage}/*

functions:
  userApi:
    handler: src/handlers/users.handler
    events:
      - http:
          path: /users
          method: post
          cors: true
      - http:
          path: /users/{userId}
          method: put
          cors: true
      - http:
          path: /users/{userId}
          method: delete
          cors: true

  birthdayChecker:
    handler: src/handlers/birthday.handler
    events:
      - schedule: rate(15 minutes)
      # Keep HTTP endpoint for manual triggers
      - http:
          path: /birthday/check
          method: post
          cors: true

custom:
  esbuild:
    bundle: true
    minify: false
    sourcemap: true
    exclude: ['aws-sdk']
    target: 'node20'
    platform: 'node'
    mainFields: ['module', 'main']
    conditions: ['node']
    packages: 'external'
    keepNames: true
    define:
      'process.env.NODE_ENV': "'production'"
  
  # Configure serverless-offline
  serverless-offline:
    httpPort: 3000
    lambdaPort: 3002
    useChildProcesses: true

  # RDS Configuration
  rds:
    host: ${ssm:/birthday-service/${self:provider.stage}/db/host, 'localhost'}
    port: ${ssm:/birthday-service/${self:provider.stage}/db/port, '5432'}
    database: ${ssm:/birthday-service/${self:provider.stage}/db/name, 'birthday_db'}
    username: ${ssm:/birthday-service/${self:provider.stage}/db/username, 'postgres'}
    password: ${ssm:/birthday-service/${self:provider.stage}/db/password, 'postgres'}

  # VPC Configuration
  vpc:
    securityGroupIds:
      - !Ref LambdaSecurityGroup
    subnetIds:
      - !Ref PublicSubnet1
      - !Ref PublicSubnet2

resources:
  Resources:
    # VPC Resources
    MainVPC:
      Type: AWS::EC2::VPC
      Properties:
        CidrBlock: 10.0.0.0/16
        EnableDnsHostnames: true
        EnableDnsSupport: true
        Tags:
          - Key: Name
            Value: ${self:service}-${self:provider.stage}

    # Public Subnets (for Lambda)
    PublicSubnet1:
      Type: AWS::EC2::Subnet
      Properties:
        VpcId: !Ref MainVPC
        AvailabilityZone: ${self:provider.region}a
        CidrBlock: 10.0.1.0/24
        MapPublicIpOnLaunch: true

    PublicSubnet2:
      Type: AWS::EC2::Subnet
      Properties:
        VpcId: !Ref MainVPC
        AvailabilityZone: ${self:provider.region}b
        CidrBlock: 10.0.2.0/24
        MapPublicIpOnLaunch: true

    # Private Subnet (for RDS)
    PrivateSubnet1:
      Type: AWS::EC2::Subnet
      Properties:
        VpcId: !Ref MainVPC
        AvailabilityZone: ${self:provider.region}a
        CidrBlock: 10.0.3.0/24

    # Internet Gateway
    InternetGateway:
      Type: AWS::EC2::InternetGateway

    AttachGateway:
      Type: AWS::EC2::VPCGatewayAttachment
      Properties:
        VpcId: !Ref MainVPC
        InternetGatewayId: !Ref InternetGateway

    # Route Tables
    PublicRouteTable:
      Type: AWS::EC2::RouteTable
      Properties:
        VpcId: !Ref MainVPC

    PublicRoute:
      Type: AWS::EC2::Route
      DependsOn: AttachGateway
      Properties:
        RouteTableId: !Ref PublicRouteTable
        DestinationCidrBlock: 0.0.0.0/0
        GatewayId: !Ref InternetGateway

    # Security Groups
    LambdaSecurityGroup:
      Type: AWS::EC2::SecurityGroup
      Properties:
        GroupDescription: Security group for Lambda functions
        VpcId: !Ref MainVPC
        SecurityGroupEgress:
          - IpProtocol: -1
            FromPort: -1
            ToPort: -1
            CidrIp: 0.0.0.0/0

    RDSSecurityGroup:
      Type: AWS::EC2::SecurityGroup
      Properties:
        GroupDescription: Security group for RDS instance
        VpcId: !Ref MainVPC
        SecurityGroupIngress:
          - IpProtocol: tcp
            FromPort: 5432
            ToPort: 5432
            SourceSecurityGroupId: !Ref LambdaSecurityGroup

    # RDS Instance
    BirthdayDB:
      Type: AWS::RDS::DBInstance
      Properties:
        Engine: postgres
        DBInstanceClass: db.t3.micro
        AllocatedStorage: 20
        DBName: ${self:custom.rds.database}
        MasterUsername: ${self:custom.rds.username}
        MasterUserPassword: ${self:custom.rds.password}
        VPCSecurityGroups:
          - !Ref RDSSecurityGroup
        DBSubnetGroupName: !Ref DBSubnetGroup
        PubliclyAccessible: false

    DBSubnetGroup:
      Type: AWS::RDS::DBSubnetGroup
      Properties:
        DBSubnetGroupDescription: Subnet group for Birthday Service RDS
        SubnetIds:
          - !Ref PrivateSubnet1